#!/bin/bash
if [[ $# -ne 1 ]]; then
  echo "Usage run_baldr N"
  exit 1
fi 
export BALDR_ROOT="/usr/local/etc"
setsid /usr/local/bin/baldr /usr/local/etc/def$1.toml --socket tcp://*:666$(($1+1)) 1>>/home/asg/logs/baldr/$1/log.txt 2>&1 &
