#!/bin/bash
if [[ $# -ne 1 ]]; then
  echo "Usage run_baldr_tt N"
  exit 1
fi 

setsid /usr/local/bin/baldr_tt /usr/local/etc/def$1.toml --socket tcp://*:667$1 1>>/home/asg/logs/baldr_tt/$1/log.txt 2>&1 &
