// This file is generated by make_commander_structs.py
namespace nlohmann {
template <> struct adl_serializer<Status> {
    static void to_json(json& j, const Status& p) {
        j = json::object();
        j["cam_status"] = p.cam_status;
        j["skipped_frames"] = p.skipped_frames;
        j["nbreads"] = p.nbreads;
        j["shm_error"] = p.shm_error;
        j["fps"] = p.fps;
    }
    static void from_json(const json& j, Status& p) {
        p = Status();
        j.at("cam_status").get_to(p.cam_status);
        j.at("skipped_frames").get_to(p.skipped_frames);
        j.at("nbreads").get_to(p.nbreads);
        j.at("shm_error").get_to(p.shm_error);
        j.at("fps").get_to(p.fps);
    }
   };
}
// End of file
// This file is generated by make_commander_structs.py
// Do not edit this file manually.
