// This file is generated by make_commander_structs.py
namespace nlohmann {
template <> struct adl_serializer<EncodedImage> {
    static void to_json(json& j, const EncodedImage& p) {
        j = json::object();
        j["szx"] = p.szx;
        j["szy"] = p.szy;
        j["type"] = p.type;
        j["message"] = p.message;
    }
    static void from_json(const json& j, EncodedImage& p) {
        p = EncodedImage();
        j.at("szx").get_to(p.szx);
        j.at("szy").get_to(p.szy);
        j.at("type").get_to(p.type);
        j.at("message").get_to(p.message);
    }
   };
template <> struct adl_serializer<Status> {
    static void to_json(json& j, const Status& p) {
        j = json::object();
        j["flux"] = p.flux;
        j["tx"] = p.tx;
        j["ty"] = p.ty;
        j["cnt"] = p.cnt;
    }
    static void from_json(const json& j, Status& p) {
        p = Status();
        j.at("flux").get_to(p.flux);
        j.at("tx").get_to(p.tx);
        j.at("ty").get_to(p.ty);
        j.at("cnt").get_to(p.cnt);
    }
   };
template <> struct adl_serializer<Settings> {
    static void to_json(json& j, const Settings& p) {
        j = json::object();
        j["ttg"] = p.ttg;
        j["hog"] = p.hog;
        j["hol"] = p.hol;
        j["focus_amp"] = p.focus_amp;
        j["flux_threshold"] = p.flux_threshold;
        j["gauss_hwidth"] = p.gauss_hwidth;
        j["px"] = p.px;
        j["py"] = p.py;
    }
    static void from_json(const json& j, Settings& p) {
        p = Settings();
        j.at("ttg").get_to(p.ttg);
        j.at("hog").get_to(p.hog);
        j.at("hol").get_to(p.hol);
        j.at("focus_amp").get_to(p.focus_amp);
        j.at("flux_threshold").get_to(p.flux_threshold);
        j.at("gauss_hwidth").get_to(p.gauss_hwidth);
        j.at("px").get_to(p.px);
        j.at("py").get_to(p.py);
    }
   };
}
// End of file
// This file is generated by make_commander_structs.py
// Do not edit this file manually.
