// This file is generated by make_commander_structs.py
namespace nlohmann {
template <> struct adl_serializer<EncodedImage> {
    static void to_json(json& j, const EncodedImage& p) {
        j = json::object();
        j["szx"] = p.szx;
        j["szy"] = p.szy;
        j["type"] = p.type;
        j["message"] = p.message;
    }
    static void from_json(const json& j, EncodedImage& p) {
        p = EncodedImage();
        j.at("szx").get_to(p.szx);
        j.at("szy").get_to(p.szy);
        j.at("type").get_to(p.type);
        j.at("message").get_to(p.message);
    }
   };
template <> struct adl_serializer<Status> {
    static void to_json(json& j, const Status& p) {
        j = json::object();
        j["gd_bl"] = p.gd_bl;
        j["pd_bl"] = p.pd_bl;
        j["gd_tel"] = p.gd_tel;
        j["pd_tel"] = p.pd_tel;
        j["gd_snr"] = p.gd_snr;
        j["pd_snr"] = p.pd_snr;
        j["closure_phase_K1"] = p.closure_phase_K1;
        j["closure_phase_K2"] = p.closure_phase_K2;
        j["v2_K1"] = p.v2_K1;
        j["v2_K2"] = p.v2_K2;
        j["dl_offload"] = p.dl_offload;
        j["dm_piston"] = p.dm_piston;
        j["pd_av"] = p.pd_av;
        j["pd_av_filtered"] = p.pd_av_filtered;
        j["gd_phasor_real"] = p.gd_phasor_real;
        j["gd_phasor_imag"] = p.gd_phasor_imag;
        j["test_ix"] = p.test_ix;
        j["test_n"] = p.test_n;
        j["cnt"] = p.cnt;
        j["num_ft_frames_missed"] = p.num_ft_frames_missed;
        j["locked"] = p.locked;
        j["itime"] = p.itime;
    }
    static void from_json(const json& j, Status& p) {
        p = Status();
        j.at("gd_bl").get_to(p.gd_bl);
        j.at("pd_bl").get_to(p.pd_bl);
        j.at("gd_tel").get_to(p.gd_tel);
        j.at("pd_tel").get_to(p.pd_tel);
        j.at("gd_snr").get_to(p.gd_snr);
        j.at("pd_snr").get_to(p.pd_snr);
        j.at("closure_phase_K1").get_to(p.closure_phase_K1);
        j.at("closure_phase_K2").get_to(p.closure_phase_K2);
        j.at("v2_K1").get_to(p.v2_K1);
        j.at("v2_K2").get_to(p.v2_K2);
        j.at("dl_offload").get_to(p.dl_offload);
        j.at("dm_piston").get_to(p.dm_piston);
        j.at("pd_av").get_to(p.pd_av);
        j.at("pd_av_filtered").get_to(p.pd_av_filtered);
        j.at("gd_phasor_real").get_to(p.gd_phasor_real);
        j.at("gd_phasor_imag").get_to(p.gd_phasor_imag);
        j.at("test_ix").get_to(p.test_ix);
        j.at("test_n").get_to(p.test_n);
        j.at("cnt").get_to(p.cnt);
        j.at("num_ft_frames_missed").get_to(p.num_ft_frames_missed);
        j.at("locked").get_to(p.locked);
        j.at("itime").get_to(p.itime);
    }
   };
template <> struct adl_serializer<Settings> {
    static void to_json(json& j, const Settings& p) {
        j = json::object();
        j["n_gd_boxcar"] = p.n_gd_boxcar;
        j["gd_threshold"] = p.gd_threshold;
        j["pd_threshold"] = p.pd_threshold;
        j["gd_search_reset"] = p.gd_search_reset;
        j["offload_time_ms"] = p.offload_time_ms;
        j["offload_gd_gain"] = p.offload_gd_gain;
        j["gd_gain"] = p.gd_gain;
        j["kp"] = p.kp;
        j["search_delta"] = p.search_delta;
        j["target_itime"] = p.target_itime;
        j["delay_line_type"] = p.delay_line_type;
        j["offload_mode"] = p.offload_mode;
        j["servo_mode"] = p.servo_mode;
        j["fixed_dl"] = p.fixed_dl;
        j["loglevel"] = p.loglevel;
        j["search_offset"] = p.search_offset;
    }
    static void from_json(const json& j, Settings& p) {
        p = Settings();
        j.at("n_gd_boxcar").get_to(p.n_gd_boxcar);
        j.at("gd_threshold").get_to(p.gd_threshold);
        j.at("pd_threshold").get_to(p.pd_threshold);
        j.at("gd_search_reset").get_to(p.gd_search_reset);
        j.at("offload_time_ms").get_to(p.offload_time_ms);
        j.at("offload_gd_gain").get_to(p.offload_gd_gain);
        j.at("gd_gain").get_to(p.gd_gain);
        j.at("kp").get_to(p.kp);
        j.at("search_delta").get_to(p.search_delta);
        j.at("target_itime").get_to(p.target_itime);
        j.at("delay_line_type").get_to(p.delay_line_type);
        j.at("offload_mode").get_to(p.offload_mode);
        j.at("servo_mode").get_to(p.servo_mode);
        j.at("fixed_dl").get_to(p.fixed_dl);
        j.at("loglevel").get_to(p.loglevel);
        j.at("search_offset").get_to(p.search_offset);
    }
   };
}
// End of file
// This file is generated by make_commander_structs.py
// Do not edit this file manually.
