name = "Default Configuration"

#All units are in radians and microns
[geometry] 
hole_diameter   = 9e-3
beam_x = [-0.00792,-0.0085,  0.0 ,  0.02130] #was 953
beam_y = [0.019,  -0.01484,  0.0 , -0.00015]
pix = 24.0

[servo]
#Phasor offsets in microns. Need to convert...
#gd_phasor_offset = [5.073, -2.203, 0.088, 3.855, -5.234, 2.61]
#gd_phasor_offset = [4.231, -0.176, -0.637, -4.038, -4.619, -0.78]
#gd_phasor_offset = [2.244, -0.592, -0.112, -2.498, -2.303, 0.523]
gd_phasor_offset = [-3.186, 1.048, 3.049, 3.732, -5.554, 2.061]
gd_phasor_sim_offset= [0,0,0,0,0,0]
dl_type = "off"

[wave]
K1  = 2.1 
K2  = 2.3 
