// This file is generated by make_commander_structs.py
namespace nlohmann {
template <> struct adl_serializer<EncodedImage> {
    static void to_json(json& j, const EncodedImage& p) {
        j = json::object();
        j["szx"] = p.szx;
        j["szy"] = p.szy;
        j["type"] = p.type;
        j["message"] = p.message;
    }
    static void from_json(const json& j, EncodedImage& p) {
        p = EncodedImage();
        j.at("szx").get_to(p.szx);
        j.at("szy").get_to(p.szy);
        j.at("type").get_to(p.type);
        j.at("message").get_to(p.message);
    }
   };
template <> struct adl_serializer<Status> {
    static void to_json(json& j, const Status& p) {
        j = json::object();
        j["nerrors"] = p.nerrors;
        j["nlowflux"] = p.nlowflux;
        j["flux"] = p.flux;
        j["strehl_flux"] = p.strehl_flux;
        j["meas_cl_rms"] = p.meas_cl_rms;
        j["mode_raw_rms"] = p.mode_raw_rms;
        j["mode_filt_rms"] = p.mode_filt_rms;
        j["com_raw_rms"] = p.com_raw_rms;
        j["com_clean_rms"] = p.com_clean_rms;
        j["cnt"] = p.cnt;
    }
    static void from_json(const json& j, Status& p) {
        p = Status();
        j.at("nerrors").get_to(p.nerrors);
        j.at("nlowflux").get_to(p.nlowflux);
        j.at("flux").get_to(p.flux);
        j.at("strehl_flux").get_to(p.strehl_flux);
        j.at("meas_cl_rms").get_to(p.meas_cl_rms);
        j.at("mode_raw_rms").get_to(p.mode_raw_rms);
        j.at("mode_filt_rms").get_to(p.mode_filt_rms);
        j.at("com_raw_rms").get_to(p.com_raw_rms);
        j.at("com_clean_rms").get_to(p.com_clean_rms);
        j.at("cnt").get_to(p.cnt);
    }
   };
template <> struct adl_serializer<Settings> {
    static void to_json(json& j, const Settings& p) {
        j = json::object();
        j["flux_threshold"] = p.flux_threshold;
        j["px"] = p.px;
        j["py"] = p.py;
        j["servo_mode"] = p.servo_mode;
    }
    static void from_json(const json& j, Settings& p) {
        p = Settings();
        j.at("flux_threshold").get_to(p.flux_threshold);
        j.at("px").get_to(p.px);
        j.at("py").get_to(p.py);
        j.at("servo_mode").get_to(p.servo_mode);
    }
   };
template <> struct adl_serializer<Result> {
    static void to_json(json& j, const Result& p) {
        j = json::object();
        j["status_code"] = p.status_code;
        j["data"] = p.data;
    }
    static void from_json(const json& j, Result& p) {
        p = Result();
        j.at("status_code").get_to(p.status_code);
        p.data = j.at("data");
    }
   };
template <> struct adl_serializer<MeasBase64> {
    static void to_json(json& j, const MeasBase64& p) {
        j = json::object();
        j["meas"] = p.meas;
        j["cnt"] = p.cnt;
    }
    static void from_json(const json& j, MeasBase64& p) {
        p = MeasBase64();
        j.at("meas").get_to(p.meas);
        j.at("cnt").get_to(p.cnt);
    }
   };
template <> struct adl_serializer<ModeBase64> {
    static void to_json(json& j, const ModeBase64& p) {
        j = json::object();
        j["mode"] = p.mode;
        j["cnt"] = p.cnt;
    }
    static void from_json(const json& j, ModeBase64& p) {
        p = ModeBase64();
        j.at("mode").get_to(p.mode);
        j.at("cnt").get_to(p.cnt);
    }
   };
}
// End of file
// This file is generated by make_commander_structs.py
// Do not edit this file manually.
