// This file is generated by make_commander_structs.py
namespace nlohmann {
template <> struct adl_serializer<EncodedImage> {
    static void to_json(json& j, const EncodedImage& p) {
        j = json::object();
        j["szx"] = p.szx;
        j["szy"] = p.szy;
        j["type"] = p.type;
        j["message"] = p.message;
    }
    static void from_json(const json& j, EncodedImage& p) {
        p = EncodedImage();
        j.at("szx").get_to(p.szx);
        j.at("szy").get_to(p.szy);
        j.at("type").get_to(p.type);
        j.at("message").get_to(p.message);
    }
   };
template <> struct adl_serializer<Status> {
    static void to_json(json& j, const Status& p) {
        j = json::object();
        j["flux"] = p.flux;
        j["nerrors"] = p.nerrors;
        j["nlowflux"] = p.nlowflux;
        j["cnt"] = p.cnt;
    }
    static void from_json(const json& j, Status& p) {
        p = Status();
        j.at("flux").get_to(p.flux);
        j.at("nerrors").get_to(p.nerrors);
        j.at("nlowflux").get_to(p.nlowflux);
        j.at("cnt").get_to(p.cnt);
    }
   };
template <> struct adl_serializer<Settings> {
    static void to_json(json& j, const Settings& p) {
        j = json::object();
        j["log"] = p.log;
        j["lol"] = p.lol;
        j["hog"] = p.hog;
        j["hol"] = p.hol;
        j["flux_threshold"] = p.flux_threshold;
        j["num_lomodes"] = p.num_lomodes;
        j["px"] = p.px;
        j["py"] = p.py;
        j["servo_mode"] = p.servo_mode;
    }
    static void from_json(const json& j, Settings& p) {
        p = Settings();
        j.at("log").get_to(p.log);
        j.at("lol").get_to(p.lol);
        j.at("hog").get_to(p.hog);
        j.at("hol").get_to(p.hol);
        j.at("flux_threshold").get_to(p.flux_threshold);
        j.at("num_lomodes").get_to(p.num_lomodes);
        j.at("px").get_to(p.px);
        j.at("py").get_to(p.py);
        j.at("servo_mode").get_to(p.servo_mode);
    }
   };
template <> struct adl_serializer<Result> {
    static void to_json(json& j, const Result& p) {
        j = json::object();
        j["status_code"] = p.status_code;
        j["data"] = p.data;
    }
    static void from_json(const json& j, Result& p) {
        p = Result();
        j.at("status_code").get_to(p.status_code);
        j.at("data").get_to(p.data);
    }
   };
template <> struct adl_serializer<MeasBase64> {
    static void to_json(json& j, const MeasBase64& p) {
        j = json::object();
        j["meas"] = p.meas;
    }
    static void from_json(const json& j, MeasBase64& p) {
        p = MeasBase64();
        j.at("meas").get_to(p.meas);
    }
   };
}
// End of file
// This file is generated by make_commander_structs.py
// Do not edit this file manually.
