name = "Default Configuration"

# Beam. This should be over-written as an input.
beam = 1

#Wavelength in microns
wave = 1.65

#Pixels to aim for
px = 15
py = 15

#Width with respect to the central pixel. Must be odd!
focus_amp = 0.00

# Flux threshold
flux_threshold = 1000

# meas_ref = "./baldr_jcr/meas_ref.fits"
# meas_to_modes = "./baldr_jcr/meas_to_modes.fits"
filter_coeff_in = "./baldr_jcr/filter_coeff_in.fits"
filter_coeff_out = "./baldr_jcr/filter_coeff_out.fits"
# modes_to_com = "./baldr_jcr/modes_to_com.fits"
# com_offset = "./baldr_jcr/com_offset.fits"
# com_dist_buffer = "./baldr_jcr/com_dist_buffer.fits"
# com_to_meas = "./baldr_jcr/com_to_meas.fits"

#All units are in radians and microns
[geometry] 
beam_diameter   = 3e-2
pix = 24.0

